### ISSUE TITLE
Incompatible with TypeDoc 0.22.5

### ISSUE THREAD

**Issue by jonamenk** [jonchardy/typedoc-plugin-no-inherit#28]
Breaks when used with TypeDoc 0.22.5

```
Error: The plugin typedoc-plugin-no-inherit could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/models/reflections/index' is not defined by "exports" in /workspace/node_modules/typedoc/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/workspace/node_modules/typedoc-plugin-no-inherit/dist/plugin.js:10:17)```

**Comment by carlo-quinonez** [comment]
Any chance a TypeDoc 0.22+ version of this plugin will be made?

**Comment by jonchardy** [comment]
Just updated the plugin for compatibility with 0.22, closing.
